[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
castagne = "HVmA4wiTwZHAtZvWgMqAmCLwUtXAPwa5ff9KjVvSwr8v"

[programs.devnet]
castagne = "HVmA4wiTwZHAtZvWgMqAmCLwUtXAPwa5ff9KjVvSwr8v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/castagne/*.ts"
init-fight-cfg = "ts-node scripts/init_config.ts"
create-player = "ts-node scripts/create_players.ts"
read-player = "ts-node scripts/read_players.ts"
sync = "cp -r target/idl/ ../web/web/context/idl && cp -r target/types/ ../web/web/context/types"